class DomainError(Exception): ...


class UserAlreadyExistsError(DomainError): ...


class InvalidCredentialsError(DomainError): ...


class InvalidAccessTokenError(DomainError): ...


class InvalidRefreshTokenError(DomainError): ...


class UserNotFoundError(DomainError): ...


class PermissionDeniedError(DomainError): ...


class TokenExpiredError(DomainError): ...
