class DomainError(Exception): ...


class UserAlreadyExistsError(DomainError): ...


class InvalidCredentialsError(DomainError): ...


class InvalidAccessTokenError(DomainError): ...


class InvalidRefreshTokenError(DomainError): ...


class RefreshUnavailableError(DomainError): ...


class UserNotFoundError(DomainError): ...


class PermissionDeniedError(DomainError): ...


class TokenExpiredError(DomainError): ...


class InvalidPasswordResetTokenError(DomainError): ...


class InvalidServiceKeyError(DomainError): ...
